### ISSUE TITLE
README and/or wiki link to active fork

### ISSUE THREAD

**Issue by markhu** [fredg02/extra-columns-plugin#1]
Should we add a README.md and/or wiki page linking to the active fork?

And on that fork, a README.md and/or wiki page, even with the briefest summary of how this plugin is maintained.

**Comment by fredg02** [comment]
I've added a README.md file to the active fork here: https://github.com/jenkinsci/extra-columns-plugin

Let me know if you think anything is missing.

**Comment by markhu** [comment]
Great job! Thanks!
